import test from 'node:test';
import assert from 'node:assert/strict';
import {
  createSession, progressFor, finishSession, dailyProgress, formatSeconds,
  phraseForElapsed, addPhrase, updatePhrase, VEGETATION, createInventory, awardVegetation,
  monthKey, rolloverMonthlyState, toggleInventoryItem,
} from '../src/core.js';

test('a new focus session starts with requested duration', () => { const session=createSession({minutes:25,label:'Ler'}); assert.equal(session.totalSeconds,1500); assert.equal(session.elapsedSeconds,0); assert.equal(session.label,'Ler'); assert.equal(session.status,'ready'); });
test('session progress is clamped between zero and one', () => { assert.equal(progressFor({elapsedSeconds:0,totalSeconds:60}),0); assert.equal(progressFor({elapsedSeconds:30,totalSeconds:60}),.5); assert.equal(progressFor({elapsedSeconds:99,totalSeconds:60}),1); });
test('finishing a session awards focus minutes and grows the grove', () => { const completed=finishSession(createSession({minutes:25,label:'Estudar'})); assert.equal(completed.status,'completed'); assert.equal(completed.focusMinutes,25); assert.equal(completed.growthStage,'tree'); });
test('daily progress counts only completed sessions on selected day', () => { const sessions=[{status:'completed',completedAt:'2026-09-06T10:00:00.000Z',focusMinutes:25},{status:'completed',completedAt:'2026-09-06T14:00:00.000Z',focusMinutes:10},{status:'abandoned',completedAt:'2026-09-06T16:00:00.000Z',focusMinutes:30},{status:'completed',completedAt:'2026-09-05T10:00:00.000Z',focusMinutes:40}]; assert.deepEqual(dailyProgress(sessions,'2026-09-06',60),{focused:35,goal:60,percent:58}); });
test('seconds format into zero-padded mm:ss', () => { assert.equal(formatSeconds(1500),'25:00'); assert.equal(formatSeconds(65),'01:05'); });
test('phrases rotate every 35 seconds', () => { const phrases=['Comece pequeno.','Respire e continue.','Uma coisa por vez.']; assert.equal(phraseForElapsed(phrases,0),'Comece pequeno.'); assert.equal(phraseForElapsed(phrases,35),'Respire e continue.'); assert.equal(phraseForElapsed(phrases,105),'Comece pequeno.'); });
test('phrases can be added and edited immutably', () => { const initial=['Foque no próximo passo.']; const withNew=addPhrase(initial,'Você consegue.'); assert.deepEqual(withNew,['Foque no próximo passo.','Você consegue.']); assert.deepEqual(updatePhrase(withNew,1,'Siga com calma.'),['Foque no próximo passo.','Siga com calma.']); assert.deepEqual(initial,['Foque no próximo passo.']); });
test('the Focapy catalog contains twenty distinct vegetation items', () => { assert.equal(VEGETATION.length,20); assert.equal(new Set(VEGETATION.map(item=>item.id)).size,20); });
test('longer sessions award rarer vegetation and inventory has no cap', () => { let inventory=createInventory(); const short=awardVegetation(inventory,10,7); assert.equal(short.item.rarity,'comum'); const long=awardVegetation(short.inventory,120,7); assert.ok(['rara','lendária'].includes(long.item.rarity)); inventory=long.inventory; for(let index=0;index<100;index+=1) inventory=awardVegetation(inventory,25,index).inventory; assert.ok(Object.values(inventory).reduce((sum,count)=>sum+count,0)>=102); });
test('month rollover archives the previous landscape as Compromisso and starts a clean month', () => { const state={monthKey:'2026-08',inventory:{clover:3,redwood:1},sessions:[{id:'s1'}],commitments:[]}; const rolled=rolloverMonthlyState(state,'2026-09'); assert.equal(rolled.monthKey,'2026-09'); assert.deepEqual(rolled.inventory,{}); assert.equal(rolled.commitments.length,1); assert.equal(rolled.commitments[0].title,'Compromisso'); assert.equal(rolled.commitments[0].monthKey,'2026-08'); assert.deepEqual(rolled.commitments[0].inventory,{clover:3,redwood:1}); assert.equal(rolled.commitments[0].sessionsCount,1); });
test('same month does not archive or erase current plants', () => { const state={monthKey:'2026-09',inventory:{daisy:2},sessions:[],commitments:[]}; assert.deepEqual(rolloverMonthlyState(state,'2026-09'),state); });
test('inventory items can be toggled inactive without changing their quantity', () => { const inactive=toggleInventoryItem({},'daisy'); assert.deepEqual(inactive,{daisy:true}); assert.deepEqual(toggleInventoryItem(inactive,'daisy'),{}); });
